apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: new-structure-secrets
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MV0id/Argo.git
        revision: main
        files:
          - path: new_structure_secrets/stage/**/clusters.yaml
    - git:
        repoURL: https://github.com/MV0id/Argo.git
        revision: main
        files:
          - path: new_structure_secrets/prod/**/clusters.yaml
  template:
    metadata:
      name: "{{cluster}}-{{namespace}}-secrets-new"
    spec:
      project: secrets
      source:
        repoURL: https://github.com/MV0id/Argo.git
        targetRevision: main
        path: "{{path}}/{{namespace}}"
      destination:
        server: "{{url}}"
        namespace: "{{namespace}}"
      ignoreDifferences:
        - group: "*"
          kind: "*"
          jsonPointers:
            - /metadata/uid
            - /metadata/managedFields
            - /metadata/generation
            - /metadata/resourceVersion
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions: 
            - .status  
            - .spec.data[]?.remoteRef.conversionStrategy 
            - .spec.data[]?.remoteRef.decodingStrategy    
            - .spec.data[]?.remoteRef.metadataPolicy      
            - .spec.dataFrom[]?.remoteRef.conversionStrategy 
            - .spec.dataFrom[]?.remoteRef.decodingStrategy   
            - .spec.dataFrom[]?.remoteRef.metadataPolicy     
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true