apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: catalog-namespaces-elcat
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - cluster: elcat
          url: https://github.com/MV0id/Argo.git
  template:
    metadata:
      name: 'catalog-namespaces-{{ cluster }}'
    spec:
      destination:
        namespace: catalog-namespaces-elcat
        server: '{{ url }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=false
        - ApplyOutOfSyncOnly=false
        - Delete=false
      project: services
      source:
        directory:
          recurse: true
        path: k8s/namespaces-elcat
        repoURL: https://github.com/MV0id/Argo.git
        targetRevision: main
