---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaces-common
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/MV0id/Argo.git
      revision: main
      files:
      - path: helm-charts/helm-namespaces/namespaces/**/targets.yaml
  template:
    metadata:
      name: 'NS-{{ namespace }}-{{ cluster }}'
    spec:
      project: services
      source:
        repoURL: https://github.com/MV0id/Argo.git
        targetRevision: main
        path: 'helm-charts/helm-namespaces/namespaces/{{ namespace }}'
      destination:
        namespace: '{{ namespace }}'
        server: '{{ url }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
