{{- $cluster := .Values.cluster }}
{{- $files := .Files.Glob "namespaces/**/targets.yaml" }}
{{- $seen := dict }}

{{- range $path, $file := $files }}
  {{- $targets := fromYaml ($file | toString) }}

  {{- range $targets }}
    {{- if eq .cluster $cluster }}

      {{- $ns := .namespace }}

      {{- if not (hasKey $seen $ns) }}
        {{- $_ := set $seen $ns true }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-catalog
  namespace: {{ $ns }}
      {{- end }}

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ $ns }}
spec:
  provider:
    vault:
      server: "https://vault-catalog-wbx.wb.ru/"
      path: "prod"
      version: "v2"
      auth:
        jwt:
          path: "k8s.{{ $cluster }}.jwt"
          role: "k8s-{{ $cluster }}-jwt-{{ $ns }}"
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "vault-catalog"
            audiences:
              - vault
            expirationSeconds: 600

    {{- end }}
  {{- end }}
{{- end }}