apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: prod-search-testns-reg
spec:
  hard:
    limits.cpu: "40"
    limits.memory: 15Gi
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1Gi
