---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-one
  namespace: prod-search-testns-reg
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-one
  data:
  - secretKey: kluch
    remoteRef:
      key: '111'
      property: kluch
